### ISSUE TITLE
Error while loading the presentation

### ISSUE THREAD

**Issue by smxsm** [twasyl/SlideshowFX#31]
I have saved and closed my first presentation (I wasn't able to add more slides, so I figured I just re-open it), but now when I try to open it, all I get is "Error while loading the presentation" :( If I open "Display logs", there is nothing to see... I have also tried to find any log file on disk but couldn't find anything. 
So how do I find out what is wrong with the presentation? The *.sfx file is binary, so no chance to see problems in there, either ....
I am running version 1.4 on MacOS with Java 1.8.0_112.

**Comment by twasyl** [comment]
Hello,

Thanks for using SlideshowFX. Could you try to click on the message "Error while loading the presentation"? It should display the error. If the message disappear, you can click on the bottom left progress bar to display all messages and then find the error message and click on it.
If the error isn't clear to you, could you attach your presentation to this thread so I can see what I can do asap?
Thanks

**Comment by smxsm** [comment]
Hi, thanks for the fast reply! I've tried to click on the error message before, but I guess I was too late... but the progress bar click worked, thanks for the hint - the error is:

> The configuration file does not exist
java.io.FileNotFoundException: The configuration file does not exist
	at com.twasyl.slideshowfx.engine.AbstractEngine.readConfiguration(AbstractEngine.java:81)
	at com.twasyl.slideshowfx.engine.AbstractEngine.readConfiguration(AbstractEngine.java:74)
	at com.twasyl.slideshowfx.engine.presentation.PresentationEngine.loadArchive(PresentationEngine.java:268)
	at com.twasyl.slideshowfx.concurrent.LoadPresentationTask.call(LoadPresentationTask.java:37)
	at com.twasyl.slideshowfx.concurrent.LoadPresentationTask.call(LoadPresentationTask.java:22)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

How does it find the configuration file? I saw that it creates some temp. folders for every presentation, e.g. "/private/var/folders/gq/gmt7r86s0y32qt6n9bccpvsh0000gn/T/sfx-1488358426298" on MAC... is that path stored in the *.sfx file?
I'll add my presentation here for reference - do you need one of the temp. folders, too?
Thanks for your help!

[Docker.sfx.zip](https://github.com/twasyl/SlideshowFX/files/819595/Docker.sfx.zip)

**Comment by twasyl** [comment]
Hello,

Thank you for providing the feedback. The problem comes from the fact the configuration file of the template is missing. Indeed, in your presentation you don't have the `template-config.json` in it. This mandatory file indicates to SlideshowFX where to find the slides' templates, and a lot of configuration elements. Did you erase it yourself?
You can find it in the template you used to create your presentation. You can add it into your presentation and it should be working. To add it, you can simply unzip your `Docker.sfx` (as it is a simple zip ranamed to .sfx) and put the `template-config.json` at the root of archive.
There is also another problem with your presentation: there is no `template.html` file in it.
Which template did you use and have you performed some modification on it?

To answer you other questions: the temporaries folders are simply the unzipping of your presentation. SlideshowFX works with those folders in order to avoid writing to the presentation file until you hit the Save button. You can look into the latest modified folder to see if you have the `template-config.json` and `template.html` files.

Cheers.

**Comment by smxsm** [comment]
Hi, ah, thanks for the insights :) Haha, didn't realize that .sfx are just Zip-Files, sorry ... in fact, there were some other files missing, e.g. resource images, *.js files etc.
I have copied everything back (unzipped the template I used, re-added the slide images etc.) and now everything is back and working again :)
I have no idea how that happened though - I didn't delete anything manually.

What I did was download the available templates manually from Github since there were no templates provided in the installation, then I chose the "dark-template" from my local download folder to create my presentation.
Looks like the resources from the templates and also the images I've added to the slides weren't saved in the *.sfx file at all ... as I wrote earlier I had problems adding new slides and then saved / reopened the presentation - and then the resources / template files were lost somehow it seems.

Anyhow, thanks for your help, my presentation is working now again now that I have put everything back into the *sfx / zip file!

**Comment by twasyl** [comment]
Hi,

Great you could retrieve your presentation. It is strange the files weren't saved. I will try to investigate how it could be possible to improve the save of each presentation.

Cheers
